### ISSUE TITLE
get_next_snapshot() bug

### ISSUE THREAD

**Issue by i2** [ashos/ashos#82]
In a fresh install, the following error appears:

![image](https://user-images.githubusercontent.com/3228126/192793864-ddad637a-155d-48b0-b226-1e7833718d6d.png)

To reproduce this:
- Do a fresh install of AshOS (any distro)
- Boot into base snapshot
- sudo ash clone 0
- DONOT run any `ash deploy` commands
- sudo ash del 1 will cause an error regarding get_next_snapshot() as there is no "snapshot-deploy-aux" yet

Preliminary fix would be to comment 2 lines at: https://github.com/ashos/ashos/blob/665329c65a1c4ada0d2cf9ff49f7746034314ed0/src/ashpk_core.py#L251-L252

Notes:
- Currently deployed snapshot is "snapshot-deploy"
- "snapshot-deploy-aux" doesn't exist as no deploy command has been run yet

**Comment by CuBeRJAN** [comment]
I'm on it!
