### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by vireakvibol** [ashos/ashos#95]
Installing with latest archiso on virtualbox with bios
Partition is already format to btrfs with `mkfs.btrfs -f /dev/sda1`
`python3 setup.py /dev/sda1 /dev/sda`

**Comment by i2** [comment]
Thanks for reporting an issue. Can you please include more info about your computer, all the steps you took that result in this error etc. So I can reproduce it. As it is, I can't reproduce it unfortunately.

**Comment by vireakvibol** [comment]
setup it on virtualbox and don't pick efi mode
1. start partitioning
all drive dedicated to btrfs /dev/sda1
2. clone repo
3. install command `python3 setup.py /dev/sda1 /devsda`

Error: IndexError: list index out of range
